import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header>
        <Link href='/' className='text-xl bg-gradient-to-r from-indigo-700 to-sky-500 bg-clip-text text-transparent'> Marcos</Link>
      </header>
        <main>{children}</main>
        </body>
    </html>
  )
}
